<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <?php echo $this->headMeta(); ?>
  <?php echo $this->headTitle();  ?>
  <meta name="keywords" content="Zend Framework 2 MongoDB" />
  <meta name="description" content="This is a research project of Zend Framework 2.0" />
  <?php echo $this->headLink()->prependStylesheet('/css/style.css'); ?>
</head>
<body>
  <div id="logo">
    <h1><a href="invoice/index">Project Alfa</a></h1>
    <p><em>This is a research project of Zend Framework 2.0</em></p>
  </div>
  <hr />
  <!-- end #logo -->
  <div id="header">
    <div id="menu">
      <ul>
        <li><a href="index/index/index" class="first">Home</a></li>
        <li class="current_page_item"><a href="invoice/index/index">Invoice</a></li>
        <li><a href="#">User</a></li>
      </ul>
    </div>
    <!-- end #menu -->
    <div id="search">
      <form method="get" action="">
        <fieldset>
        <input type="text" name="s" id="search-text" size="15" />
        <input type="submit" id="search-submit" value="GO" />
        </fieldset>
      </form>
    </div>
    <!-- end #search -->
  </div>
  <!-- end #header -->
  <!-- end #header-wrapper -->
  <div id="page">
    <div id="content">
      <?php echo $this->raw('content'); ?>      
    </div><!-- end #content -->
    <div id="sidebar">
      <ul>
        <li>
          <h2>Aliquam tempus</h2>
          <p>Mauris vitae nisl nec metus placerat perdiet est. Phasellus dapibus semper urna. Pellentesque ornare, orci in consectetuer hendrerit, volutpat.</p>
        </li>
        <li>
          <h2>Pellenteque ornare </h2>
          <ul>
            <li><a href="#">Nec metus sed donec</a></li>
            <li><a href="#">Magna lacus bibendum mauris</a></li>
            <li><a href="#">Velit semper nisi molestie</a></li>
            <li><a href="#">Eget tempor eget nonummy</a></li>
            <li><a href="#">Nec metus sed donec</a></li>
            <li><a href="#">Velit semper nisi molestie</a></li>
            <li><a href="#">Eget tempor eget nonummy</a></li>
            <li><a href="#">Nec metus sed donec</a></li>
          </ul>
        </li>
      </ul>
    </div>
    <!-- end #sidebar -->
    <div style="clear: both;">&nbsp;</div>
  </div>
  <!-- end #page -->
  <div id="footer">
    <p>Copyright (c) 2011 Tomas Dermisek. All rights reserved. Design by <a href="http://www.freecsstemplates.org/">Free CSS Templates</a>.</p>
  </div>
  <!-- end #footer -->
</body>
</html>
